import type { IrisTheme } from './types'

export const darkTheme: IrisTheme = {
  name: 'iris-dark',
  type: 'dark',
  colors: {
    'iris.background': '#0b1020',
    'iris.foreground': '#e2e8f0',
    'iris.surface': '#111827',
    'iris.surface.hover': '#1f2937',
    'iris.border': '#1f2937',
    'iris.muted': '#94a3b8',
    'iris.primary': '#818cf8',
    'iris.primary.foreground': '#0b1020',
    'iris.accent': '#a78bfa',
    'iris.danger': '#f87171',
    'iris.danger.subtle': '#450a0a',
    'iris.success': '#34d399',
    'iris.warning': '#fbbf24',
    'iris.warning.foreground': '#451a03',
    'iris.info': '#60a5fa',
    'iris.on.color': '#ffffff', // theme-stable: sole consumer = user-colored calendar event chips (dark.ts + light.ts identical)
    'iris.muted.subtle': '#1f2937',
    'iris.surface.selected': '#1e1b4b',
    'iris.primary.ghost': '#1e1b4b',
    'iris.font.family': "'Inter', system-ui, sans-serif",
    'iris.font.mono': "'JetBrains Mono', 'Fira Code', monospace",
    'iris.font.size.xs': '12px',
    'iris.font.size.sm': '13px',
    'iris.font.size.md': '14px',
    'iris.font.size.base': '15px',
    'iris.font.size.lg': '16px',
    'iris.font.size.xl': '18px',
    'iris.font.size.2xl': '20px',
    'iris.font.size.3xl': '24px',
    'iris.font.size.4xl': '30px',
    'iris.font.weight.regular': '400',
    'iris.font.weight.medium': '500',
    'iris.font.weight.semibold': '600',
    'iris.font.weight.bold': '700',
    'iris.font.line.height.sm': '1.4',
    'iris.font.line.height.md': '1.5',
    'iris.font.line.height.lg': '1.6',
    'iris.font.letter.spacing.tight': '-0.01em',
    'iris.font.letter.spacing.normal': '0em',
    'iris.font.letter.spacing.wide': '0.02em',
  },
  spacing: {
    'iris.gap.sm': 4,
    'iris.gap.md': 8,
    'iris.gap.lg': 16,
    // padding.*/gap.* = dense control scale for 28–34px controls; padding.sm=6 is an
    // intentional library-scale exception outside the 8pt page grid (micro-component
    // band 4–8px, ui-specs/geometry.md) — ~30 primitives + plugin chips consume it.
    'iris.padding.sm': 6,
    'iris.padding.md': 12,
    'iris.padding.lg': 20,
    'iris.masonry.gap': 16,
    'iris.breadcrumb.gap': 8,
    'iris.space.xxs': 4,
    'iris.space.xs': 8,
    'iris.space.sm': 12,
    'iris.space.md': 16,
    'iris.space.lg': 20,
    'iris.space.xl': 24,
    'iris.space.2xl': 32,
    'iris.space.3xl': 40,
    'iris.space.4xl': 48,
    'iris.space.5xl': 64,
    'iris.control.height.sm': 28,
    'iris.control.height.md': 34,
    'iris.control.height.lg': 40,
  },
  radii: {
    'iris.radius.sm': 2,
    'iris.radius.md': 6,
    'iris.radius.lg': 12,
  },
  shadows: {
    'iris.shadow.sm': '0 1px 3px 0 rgb(0 0 0 / 0.4)',
    'iris.shadow.md': '0 4px 6px -1px rgb(0 0 0 / 0.4)',
    'iris.shadow.lg': '0 10px 15px -3px rgb(0 0 0 / 0.4)',
    'iris.shadow.xl': '0 24px 48px -16px rgb(0 0 0 / 0.6), 0 8px 16px -4px rgb(0 0 0 / 0.4)',
  },
  zIndex: {
    'iris.z.dropdown': 1000,
    'iris.z.sticky': 1020,
    'iris.z.fixed': 1030,
    'iris.z.modalBackdrop': 1040,
    'iris.z.modal': 1050,
    'iris.z.popover': 1060,
    'iris.z.tooltip': 1070,
    'iris.z.toast': 1080,
  },
  transitions: {
    'iris.transition.fast': '150ms',
    'iris.transition.normal': '250ms',
    'iris.transition.slow': '400ms',
    'iris.transition.ease': 'cubic-bezier(0.4, 0, 0.2, 1)',
    'iris.transition.spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  },
}
