import type { IrisTheme } from './types'

export const darkTheme: IrisTheme = {
  name: 'iris-dark',
  type: 'dark',
  colors: {
    'iris.background': '#0b1020',
    'iris.foreground': '#e2e8f0',
    'iris.surface': '#111827',
    'iris.surface.hover': '#1f2937',
    'iris.border': '#1f2937',
    'iris.muted': '#94a3b8',
    'iris.primary': '#818cf8',
    'iris.primary.foreground': '#0b1020',
    'iris.accent': '#a78bfa',
    'iris.danger': '#f87171',
    'iris.danger.subtle': '#450a0a',
    'iris.success': '#34d399',
    'iris.warning': '#fbbf24',
    'iris.info': '#60a5fa',
    'iris.muted.subtle': '#1f2937',
    'iris.surface.selected': '#1e1b4b',
    'iris.primary.ghost': '#1e1b4b',
    'iris.font.family': "'Inter', system-ui, sans-serif",
    'iris.font.mono': "'JetBrains Mono', 'Fira Code', monospace",
    'iris.font.size.sm': '13px',
    'iris.font.size.md': '15px',
    'iris.font.size.lg': '18px',
  },
  spacing: {
    'iris.gap.sm': 4,
    'iris.gap.md': 8,
    'iris.gap.lg': 16,
    'iris.padding.sm': 6,
    'iris.padding.md': 12,
    'iris.padding.lg': 20,
    'iris.masonry.gap': 16,
    'iris.breadcrumb.gap': 8,
  },
  radii: {
    'iris.radius.sm': 2,
    'iris.radius.md': 6,
    'iris.radius.lg': 12,
  },
  shadows: {
    'iris.shadow.sm': '0 1px 3px 0 rgb(0 0 0 / 0.4)',
    'iris.shadow.md': '0 4px 6px -1px rgb(0 0 0 / 0.4)',
    'iris.shadow.lg': '0 10px 15px -3px rgb(0 0 0 / 0.4)',
  },
  zIndex: {
    'iris.z.dropdown': 1000,
    'iris.z.sticky': 1020,
    'iris.z.fixed': 1030,
    'iris.z.modalBackdrop': 1040,
    'iris.z.modal': 1050,
    'iris.z.popover': 1060,
    'iris.z.tooltip': 1070,
    'iris.z.toast': 1080,
  },
  transitions: {
    'iris.transition.fast': '150ms',
    'iris.transition.normal': '250ms',
    'iris.transition.slow': '400ms',
    'iris.transition.ease': 'cubic-bezier(0.4, 0, 0.2, 1)',
    'iris.transition.spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  },
}
