import type { IrisTheme } from './types'

export const lightTheme: IrisTheme = {
  name: 'iris-light',
  type: 'light',
  colors: {
    'iris.background': '#ffffff',
    'iris.foreground': '#0f172a',
    'iris.surface': '#f8fafc',
    'iris.surface.hover': '#f1f5f9',
    'iris.border': '#e2e8f0',
    'iris.muted': '#64748b',
    'iris.primary': '#6366f1',
    'iris.primary.foreground': '#ffffff',
    'iris.accent': '#8b5cf6',
    'iris.danger': '#ef4444',
    'iris.danger.subtle': '#fef2f2',
    'iris.success': '#10b981',
    'iris.warning': '#f59e0b',
    'iris.info': '#3b82f6',
    'iris.muted.subtle': '#e2e8f0',
    'iris.surface.selected': '#eef2ff',
    'iris.primary.ghost': '#eef2ff',
    'iris.font.family': "'Inter', system-ui, sans-serif",
    'iris.font.mono': "'JetBrains Mono', 'Fira Code', monospace",
    'iris.font.size.sm': '13px',
    'iris.font.size.md': '15px',
    'iris.font.size.lg': '18px',
  },
  spacing: {
    'iris.gap.sm': 4,
    'iris.gap.md': 8,
    'iris.gap.lg': 16,
    'iris.padding.sm': 6,
    'iris.padding.md': 12,
    'iris.padding.lg': 20,
    'iris.masonry.gap': 16,
    'iris.breadcrumb.gap': 8,
  },
  radii: {
    'iris.radius.sm': 2,
    'iris.radius.md': 6,
    'iris.radius.lg': 12,
  },
  shadows: {
    'iris.shadow.sm': '0 1px 3px 0 rgb(0 0 0 / 0.1)',
    'iris.shadow.md': '0 4px 6px -1px rgb(0 0 0 / 0.1)',
    'iris.shadow.lg': '0 10px 15px -3px rgb(0 0 0 / 0.1)',
  },
  zIndex: {
    'iris.z.dropdown': 1000,
    'iris.z.sticky': 1020,
    'iris.z.fixed': 1030,
    'iris.z.modalBackdrop': 1040,
    'iris.z.modal': 1050,
    'iris.z.popover': 1060,
    'iris.z.tooltip': 1070,
    'iris.z.toast': 1080,
  },
  transitions: {
    'iris.transition.fast': '150ms',
    'iris.transition.normal': '250ms',
    'iris.transition.slow': '400ms',
    'iris.transition.ease': 'cubic-bezier(0.4, 0, 0.2, 1)',
    'iris.transition.spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  },
}
